on:
  push:
    branches:
      - main

name: Unit tests

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unix release build
        run: cargo test --release
